Retry `sacct` in case of failure
If `sacct` fails (e.g. when it can't contact the database), continue retrying every 5s for 5 attempts before total failure.

diff --git a/profiles/slurm/status b/profiles/slurm/status
--- a/profiles/slurm/status
+++ b/profiles/slurm/status
@@ -2,7 +2,35 @@
 
 JOB_ID="$1"
 
-STATE=$(sacct --format state --parsable2 --jobs "${JOB_ID}" | tail -n1)
+# Ensure provided JOB_ID is a number
+re='^[0-9]+$'
+if ! [[ ${JOB_ID} =~ $re ]] ; then
+   >&2 echo "ERROR: JOB_ID Not a number: ${JOB_ID}"
+   exit 1
+fi
+
+# Generic retry function with up to 5 retry attempts
+function retry {
+  local max_attempts=5
+  local delay_sec=5
+
+  local attempt=1
+  while true; do
+    "$@" && break || {
+      if [[ ${attempt} -lt ${max_attempts} ]]; then
+        >&2 echo "WARN: Command ($@) failed attempt ${attempt} of ${max_attempts}:"
+        sleep ${delay_sec}
+      else
+        >&2 echo "ERROR: Command ($@) failed after ${attempt} attempt(s)."
+        exit 1
+      fi
+      ((attempt++))
+    }
+  done
+}
+
+set -o pipefail
+STATE=$(retry sacct --format state --parsable2 --jobs "${JOB_ID}" --noheader | fgrep -v -e '.batch')
 
 case "${STATE}" in
 	*RUNNING*|*PENDING*|*SUSPENDED*|*COMPLETING*|*CONFIGURING* )
