Retry job submission when  fails

diff --git a/profiles/slurm/submit b/profiles/slurm/submit
--- a/profiles/slurm/submit
+++ b/profiles/slurm/submit
@@ -56,6 +56,26 @@ fi
 export DEP_STRING
 export SBATCH_ARGS
 
-# need to return just the job ID part to enable snakemake to build dependencies correctly
-# $@ should still contain the job execution script generated by snakemake
-sbatch ${DEP_STRING} ${SBATCH_ARGS} $@ | cut -f4 -d' '
+# Generic retry function with up to 5 retry attempts
+function retry {
+  local max_attempts=5
+  local delay_sec=5
+
+  local attempt=1
+  while true; do
+    "$@" && break || {
+      if [[ ${attempt} -lt ${max_attempts} ]]; then
+        >&2 echo "WARN: Command ($@) failed attempt ${attempt} of ${max_attempts}:"
+        sleep ${delay_sec}
+      else
+        >&2 echo "ERROR: Command ($@) failed after ${attempt} attempt(s)."
+        exit 1
+      fi
+      ((attempt++))
+    }
+  done
+}
+
+set -o pipefail
+JOBID=$(retry sbatch ${DEP_STRING} ${SBATCH_ARGS} $@ | cut -f4 -d' ')
+echo -n "${JOBID}"
